### ISSUE TITLE
Using Wiki External Filter with Redmine v1.0.3 (2010-10-31)

### ISSUE THREAD

**Issue by siamak-haschemi** [ndl/wiki_external_filter#4]
Hello,

I wonder if you have the patch files to let Wiki External Filter work with Redmine v1.0.3 (2010-10-31)

Cheers,
Siamak

**Comment by ndl** [comment]
I do have patches for Redmine 1.0.2, see [here](http://www.ndl.kiev.ua/content/redmine-wiki-external-filter-plugin) but I have not checked if they work OK for 1.0.3 or not - you might give them a try, though.

**Comment by siamak-haschemi** [comment]
I will give it a try, but on a first sight, the affected files (lib/redmine/wiki_formatting.rb
, redmine/app/helpers/application_helper.rb
) seem to be changed.

**Comment by siamak-haschemi** [comment]
I tried it out and finally it works!

You can keep the redmine-1.0.2-macros-escaping.patch without any change. The file redmine-1.0.2-attachments.patch needs a change:

From:

<pre>
<code>
...
@@ -509,17 +509,23 @@
...
</code>
</pre>


to:

<pre>
<code>
...
@@ -495,17 +495,23 @@
...
</code>
</pre>


;-)

Cheers,
Siamak
